### ISSUE TITLE
辛苦辛苦

### ISSUE THREAD

**Issue by hsmaocn** [freedom-introvert/Research-on-Avalon-System-in-Bilibili-Comment-Area#2]
我说这个b站评论区怎么看怎么奇怪，有时吞评论确实很恶心，有些地方也做的确实不好，但也可以理解 ，毕竟现在审查比较严格。

**Comment by freedom-introvert** [comment]
告诉你一个笑话：我开发了另一个软件的插件，叫做“[YouTube发评反诈](https://github.com/freedom-introvert/YouTubeSendCommentAntiFraud)”，比b站更沙雕，更是把美国宪法狠狠的摁在地上摩擦🤡

**Comment by yaoyuan26** [comment]
人民应当有说话的正当权力

**Comment by HAMAN23333** [comment]
> 告诉你一个笑话：我开发了另一个软件的插件，叫做“[YouTube发评反诈](https://github.com/freedom-introvert/YouTubeSendCommentAntiFraud)”，比b站更沙雕，更是把美国宪法狠狠的摁在地上摩擦🤡

中美互相奔赴了
不过youtube中文被吞评的主要原因是招了一堆中国留学生，而且都是战狼得不能再战狼没有思考能力的公费留学生，同样的话我用英文说就没事
